export default {
  notfound: "/assets/images/404.svg",
  logo: "/vercel.svg",
  logo_img: "/assets/images/logo.png",
  line1: "/assets/images/line-1.png",
  line2: "/assets/images/line-2.png",
  avatarMain: "/assets/images/avatar-main.jpg",
  reactJs: "/assets/images/react-js.svg",
  html: "/assets/images/html5.svg",
  css: "/assets/images/css3.svg",
  about: "/assets/images/about.jpg",
  aboutbg: "/assets/images/aboutbg.png",
  heroBg: "/assets/images/heroBg.png",
  workBg: "/assets/images/workBg.png",
  projectBg: "/assets/images/projectBg.png",
  ofcIcon: "/assets/images/ofcIcon.png",
  projectIntel: "/assets/images/project-intel.png",
  projectShopdrop: "/assets/images/project-shopdrop.png",
  projectPrivy: "/assets/images/project-privy.png",
  projectEasternrailway: "/assets/images/project-easternrailway.png",
  projectLiefermarsadmin: "/assets/images/project-liefermarsadmin.png",
  projectQuotegreen: "/assets/images/project-quotegreen.png",
  projectShowcode: "/assets/images/project-showcode.png",
  projectGanesh: "/assets/images/project-ganesh.png",
  projectJohnson: "/assets/images/project-johnson.jpg",
  projectBullshift: "/assets/images/project-bullshift.jpg",
  projectPolpick: "/assets/images/project-polpick.jpg"
};
